backend:
  name: git-gateway
  branch: main
media_folder: "public/assets/media"
public_folder: "/assets/media"
collections:
  - name: "services"
    label: "Tjänst"
    folder: "src/services"
    create: true
    slug: "{{slug}}"
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Sortering", name: "sort", widget: "number", default: 1, value_type: "int", min: 1, max: 101, step: 1}
      - { label: "Beskrivning", name: "description", widget: "string" }
      - { label: "Författare", name: "author", widget: "string" }
      - { label: "Datum", name: "date", widget: "datetime" }
      - { label: "Taggar", name: "tags", widget: "list", default: ["post"] }
      - { label: "Bildtext", name: "imageAlt", widget: "string" }
      - { label: "Bild", name: "image", widget: "image" }
      - { label: "Brödtext", name: "body", widget: "markdown"}
  - name: "testimonials"
    label: "Vittnesmål"
    folder: "src/testemonials"
    create: true
    slug: "{{slug}}"
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Beskrivning", required: false, name: "description", widget: "string" }
      - { label: "Författare", name: "author", widget: "string" }
      - { label: "Datum", name: "date", widget: "datetime" }
      - { label: "Taggar", name: "tags", widget: "list", default: ["recension"] }
      - { label: "Bildtext", required: false, name: "imageAlt", widget: "string" }
      - { label: "Bild", required: false, name: "image", widget: "image" }
      - { label: "Brödtext", name: "body", widget: "markdown"}